import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getToolBySlug, SITE_CONFIG } from "@/lib/tools";
import { ToolPageShell } from "@/components/tools/ToolPageShell";
import { QrCodeGeneratorTool } from "@/components/tools/QrCodeGeneratorTool";

const TOOL_SLUG = "qr-code-generator";

export const metadata: Metadata = {
  title: "QR Code Generator — Create Custom PNG & SVG QR Codes Online",
  description:
    "Generate scannable QR codes from any URL or text instantly in your browser. Customize size and colors, check contrast, and download high-resolution PNG or SVG files.",
  alternates: {
    canonical: `${SITE_CONFIG.url}/tools/${TOOL_SLUG}`,
  },
  openGraph: {
    title: `QR Code Generator | ${SITE_CONFIG.name}`,
    description:
      "Generate scannable QR codes from any URL or text instantly in your browser with PNG and SVG export.",
    url: `${SITE_CONFIG.url}/tools/${TOOL_SLUG}`,
    type: "website",
  },
};

const INSTRUCTIONS = [
  {
    stepTitle: "Enter a URL or Text",
    stepDescription:
      "Type or paste your website link, contact string, or plain text (up to 2,000 characters) into the input box.",
  },
  {
    stepTitle: "Customize Size & Colors",
    stepDescription:
      "Adjust the pixel dimensions from 128px to 1024px and pick custom foreground and background hex colors.",
  },
  {
    stepTitle: "Check Scannability & Contrast",
    stepDescription:
      "Keep a dark foreground on a light background for universal camera compatibility. A built-in contrast checker alerts you if colors are too similar.",
  },
  {
    stepTitle: "Download PNG or SVG",
    stepDescription:
      "Export a crisp raster PNG image for web and slides, or download a scalable vector SVG for print and design software.",
  },
] as const;

const FAQS = [
  {
    question: "Do QR codes generated here expire?",
    answer:
      "No. The QR codes generated by this tool encode your text or URL directly into the pattern (static QR codes). They do not route through tracking redirects and never expire.",
  },
  {
    question: "Why is there a border around the QR code?",
    answer:
      "That border is the standard 4-module 'quiet zone' required by QR specifications so smartphone cameras and barcode scanners can cleanly separate the code from surrounding graphics.",
  },
  {
    question: "Should I download PNG or SVG?",
    answer:
      "Choose PNG for quick sharing in documents, emails, and websites. Choose SVG if you are placing the QR code into print layouts, posters, or vector illustration tools where infinite scaling is needed.",
  },
  {
    question: "Why did I get a contrast warning?",
    answer:
      "QR scanners rely on strong luminance separation between dark modules and the light background. Low-contrast combinations or inverted colors (light foreground on dark background) may fail on some phone cameras.",
  },
] as const;

export default function QrCodeGeneratorPage() {
  const tool = getToolBySlug(TOOL_SLUG);
  if (!tool) {
    notFound();
  }

  return (
    <ToolPageShell
      tool={tool}
      title="QR Code Generator"
      description="Create customizable, high-contrast QR codes for links and text with instant live preview and PNG or SVG downloads."
      privacyNote="QR codes are generated locally in your browser with no tracking redirects."
      instructions={INSTRUCTIONS}
      faqs={FAQS}
    >
      <QrCodeGeneratorTool />
    </ToolPageShell>
  );
}
