import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getToolBySlug } from "@/lib/tools";
import { buildPageMetadata } from "@/lib/seo";
import { ToolPageShell } from "@/components/tools/ToolPageShell";
import { QrCodeGeneratorTool } from "@/components/tools/QrCodeGeneratorTool";

const TOOL_SLUG = "qr-code-generator";

export const metadata: Metadata = buildPageMetadata({
  title: "QR Code Generator — Create Custom PNG & SVG QR Codes Online",
  description:
    "Generate scannable QR codes from any URL or text instantly in your browser. Customize size and colors, check contrast, and download high-resolution PNG or SVG files.",
  path: `/tools/${TOOL_SLUG}`,
});

const OVERVIEW =
  "The OneToolHub QR Code Generator creates static, non-expiring QR codes from website URLs, plain text, Wi-Fi notes, or contact details directly in your browser. Unlike redirect-based QR services, the generated pattern encodes your data directly into the matrix and includes a real-time WCAG luminance contrast checker so your codes remain scannable across smartphone cameras.";

const FEATURES = [
  "Instant live QR preview for URLs and text strings up to 2,000 characters.",
  "Customizable output dimensions from 128 px to 1024 px with a standard 4-module quiet zone.",
  "Custom foreground and background hex color pickers.",
  "Built-in contrast and color-inversion detector to warn against low-scannability color pairs.",
  "High-resolution raster PNG and scalable vector SVG download options.",
  "Static encoding with zero tracking redirects or expiration limits.",
] as const;

const EXAMPLES = [
  {
    title: "Website or Portfolio Link for Print Cards",
    description:
      "Enter your portfolio URL, choose a dark navy foreground (#1e1b4b) on a white background (#ffffff), and export an SVG for crisp vector printing.",
    sample: "https://example.com/portfolio",
  },
  {
    title: "Event Check-In or Conference Slide QR",
    description:
      "Generate a 512 px PNG QR code pointing to a registration form or slide deck so attendees can scan from across the room.",
    sample: "https://example.com/slides-2026",
  },
] as const;

const INSTRUCTIONS = [
  {
    stepTitle: "Enter a URL or Text",
    stepDescription:
      "Type or paste your website link, contact string, or plain text (up to 2,000 characters) into the input box.",
  },
  {
    stepTitle: "Customize Size & Colors",
    stepDescription:
      "Adjust the pixel dimensions from 128px to 1024px and pick custom foreground and background hex colors.",
  },
  {
    stepTitle: "Check Scannability & Contrast",
    stepDescription:
      "Keep a dark foreground on a light background for universal camera compatibility. A built-in contrast checker alerts you if colors are too similar.",
  },
  {
    stepTitle: "Download PNG or SVG",
    stepDescription:
      "Export a crisp raster PNG image for web and slides, or download a scalable vector SVG for print and design software.",
  },
] as const;

const FAQS = [
  {
    question: "Do QR codes generated here expire?",
    answer:
      "No. The QR codes generated by this tool encode your text or URL directly into the pattern (static QR codes). They do not route through tracking redirects and never expire.",
  },
  {
    question: "Why is there a border around the QR code?",
    answer:
      "That border is the standard 4-module 'quiet zone' required by QR specifications so smartphone cameras and barcode scanners can cleanly separate the code from surrounding graphics.",
  },
  {
    question: "Should I download PNG or SVG?",
    answer:
      "Choose PNG for quick sharing in documents, emails, and websites. Choose SVG if you are placing the QR code into print layouts, posters, or vector illustration tools where infinite scaling is needed.",
  },
  {
    question: "Why did I get a contrast warning?",
    answer:
      "QR scanners rely on strong luminance separation between dark modules and the light background. Low-contrast combinations or inverted colors (light foreground on dark background) may fail on some phone cameras.",
  },
] as const;

export default function QrCodeGeneratorPage() {
  const tool = getToolBySlug(TOOL_SLUG);
  if (!tool) {
    notFound();
  }

  return (
    <ToolPageShell
      tool={tool}
      title="QR Code Generator"
      description="Create customizable, high-contrast QR codes for links and text with instant live preview and PNG or SVG downloads."
      privacyNote="QR codes are generated locally in your browser with no tracking redirects."
      overview={OVERVIEW}
      features={FEATURES}
      examples={EXAMPLES}
      instructions={INSTRUCTIONS}
      faqs={FAQS}
    >
      <QrCodeGeneratorTool />
    </ToolPageShell>
  );
}
